-- ==============================================================================
-- Central Master Supabase SQL Migration
-- Table: hackathons
-- 
-- This script safely and idempotently ensures that the 'hackathons' table
-- supports all 17 unified hackathon detail fields, legacy backward-compatibility
-- columns, deduplication constraint (source_url), performance query indexes,
-- and Row Level Security (RLS) policies.
--
-- DO NOT EXECUTE AUTOMATICALLY. Review and run in Supabase SQL Editor if needed:
-- https://supabase.com/dashboard/project/_/sql
-- ==============================================================================

-- 1. Create table if starting from a fresh database
CREATE TABLE IF NOT EXISTS hackathons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    organizer TEXT,
    status TEXT,
    location TEXT,
    event_mode TEXT,
    start_date DATE,
    end_date DATE,
    registration_deadline DATE,
    team_size_min INT,
    team_size_max INT,
    prize TEXT,
    prize_amount NUMERIC,
    currency TEXT,
    tags TEXT[] DEFAULT '{}'::TEXT[],
    source_url TEXT NOT NULL,
    source_website TEXT,
    scraped_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Safely add any missing unified 17 fields idempotently to existing tables
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS organizer TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS event_mode TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS registration_deadline DATE;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS team_size_min INT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS team_size_max INT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS prize TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS prize_amount NUMERIC;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS currency TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}'::TEXT[];
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS source_url TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS source_website TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS scraped_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 3. Backward-compatibility columns for legacy schemas
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS event_start_date TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS event_end_date TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS location_mode TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS team_size TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS registration_link TEXT;

-- 4. Unique index on source_url for idempotent upsert & conflict resolution
CREATE UNIQUE INDEX IF NOT EXISTS idx_hackathons_source_url ON hackathons(source_url);

-- 5. Query performance indexes
CREATE INDEX IF NOT EXISTS idx_hackathons_source_website ON hackathons(source_website);
CREATE INDEX IF NOT EXISTS idx_hackathons_status ON hackathons(status);
CREATE INDEX IF NOT EXISTS idx_hackathons_start_date ON hackathons(start_date);
CREATE INDEX IF NOT EXISTS idx_hackathons_registration_deadline ON hackathons(registration_deadline);

-- 6. Enable Row Level Security (RLS)
ALTER TABLE hackathons ENABLE ROW LEVEL SECURITY;

-- 7. RLS Policies for anon / public access
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'hackathons' AND policyname = 'Allow public read access'
    ) THEN
        CREATE POLICY "Allow public read access" ON hackathons FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'hackathons' AND policyname = 'Allow public upsert access'
    ) THEN
        CREATE POLICY "Allow public upsert access" ON hackathons FOR ALL USING (true);
    END IF;
END $$;
