-- ==============================================================================
-- Supabase SQL Migration: Add Structured Hackathon Detail Fields
-- Table: hackathons
-- ==============================================================================

-- 1. Ensure table exists (if starting fresh)
CREATE TABLE IF NOT EXISTS hackathons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    name TEXT,
    source_url TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Add all structured detail fields idempotently
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS title TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS organizer TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS status TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS location TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS event_mode TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS start_date TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS end_date TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS registration_deadline TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS team_size_min INT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS team_size_max INT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS prize TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS prize_amount NUMERIC DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}'::TEXT[];
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS source_url TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS source_website TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS scraped_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

-- Backward compatibility columns for existing schemas
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS name TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS event_start_date TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS event_end_date TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS location_mode TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS team_size TEXT DEFAULT NULL;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS registration_link TEXT DEFAULT NULL;

-- 3. Ensure unique index on source_url for deduplication & conflict resolution
CREATE UNIQUE INDEX IF NOT EXISTS idx_hackathons_source_url ON hackathons(source_url);

-- 4. Enable Row Level Security (RLS) if not already enabled
ALTER TABLE hackathons ENABLE ROW LEVEL SECURITY;

-- 5. Policies for public / anon read and upsert access
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'hackathons' AND policyname = 'Allow public read access'
    ) THEN
        CREATE POLICY "Allow public read access" ON hackathons FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'hackathons' AND policyname = 'Allow public upsert access'
    ) THEN
        CREATE POLICY "Allow public upsert access" ON hackathons FOR ALL USING (true);
    END IF;
END $$;
