-- Supabase Database Migration Script for Hackathons Table
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create table if it doesn't already exist
CREATE TABLE IF NOT EXISTS hackathons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    organizer TEXT,
    status TEXT,
    location TEXT,
    event_mode TEXT,
    start_date DATE,
    end_date DATE,
    registration_deadline DATE,
    team_size_min INT,
    team_size_max INT,
    prize TEXT,
    prize_amount NUMERIC,
    currency TEXT,
    tags TEXT[] DEFAULT '{}'::TEXT[],
    source_url TEXT NOT NULL,
    source_website TEXT,
    scraped_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Safe Column Additions for Existing Tables
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS organizer TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS event_mode TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS registration_deadline DATE;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS team_size_min INT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS team_size_max INT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS prize TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS prize_amount NUMERIC;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS currency TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}'::TEXT[];
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS source_url TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS source_website TEXT;
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS scraped_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE hackathons ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 3. Unique Index on source_url for Idempotent Deduplication & Upsert
CREATE UNIQUE INDEX IF NOT EXISTS idx_hackathons_source_url ON hackathons(source_url);

-- 4. Fast Query Indexes
CREATE INDEX IF NOT EXISTS idx_hackathons_source_website ON hackathons(source_website);
CREATE INDEX IF NOT EXISTS idx_hackathons_status ON hackathons(status);
CREATE INDEX IF NOT EXISTS idx_hackathons_start_date ON hackathons(start_date);
CREATE INDEX IF NOT EXISTS idx_hackathons_registration_deadline ON hackathons(registration_deadline);
